### ISSUE TITLE
Edit bouton visible on https://docs.pieces.app/ for non admin user

### ISSUE THREAD

**Issue by EveCrystali** [pieces-app/support#153]
### Software

Desktop Application, Pieces OS, Web Extension

### Operating System

Windows

### Your Pieces OS Version

8.1.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Front-end issue on the doc page :  the edit link is visible even for non admin user (bottom left of the screenshot).
![image](https://github.com/pieces-app/support/assets/34349789/4c66955f-c79c-4c06-866a-3c9735f32c90)

**Comment by mason-at-pieces** [comment]
Hey there! We actually have this edit button configured so that community members just like yourself can contribute to our docs!

If you find a typo or wish we had more details about a feature, you can edit a page and make those changes.

We do have a review process in place so that any contributions to our docs have to be in a pr that is reviewed by myself before it can be merged into production 👍

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.
