### ISSUE TITLE
Can’t copy individual text from the copilot chats

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#180]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

9.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I can't select part of a copilot chat if I want to copy part of it, I can only copy the whole thing using the copy button

**Comment by thistlillo** [comment]
+1 here. This is so uncomfortable that I stopped using the app.

**Comment by rosie-at-pieces** [comment]
@thistlillo I hate to hear that! I'm sorry it is causing you so much trouble. While we work to figure this out, please note that you can copy the whole message using the copy icon if you hover over the message. Also, this issue is limited to the Desktop app, so you should be able to select parts of a conversation if you have the Pieces extension in your IDE and/or browser.

**Comment by osyyyS** [comment]
+1 here. I have the same issue on windows 11.

**Comment by osyyyS** [comment]
Works fine now on Windows 11(2.12.1). Thanks!

**Comment by itz-shubham** [comment]
+ 1 here. I am also facing this issue every time in my mac **vs code.** 
I have to copy the whole code by the copy button... paste it into a file, cut specific code from there... then use. 

Don't you think it's very unproductive thing to do when you are using a "productive app" 🙂

**Comment by mdeeter** [comment]
I'm having the same issue on Mac using VS code...

When I use Pieces Copilot in Visual Studio Code and try to copy anything by highlighting text inside a code block of suggested code to use... the copy function will not work.  The only way I can seem to get any of the suggested code is to use the 'copy' link at the top-right of the code block... and then paste it all in and delete everything I don't want.

This becomes even more annoying when trying to copy just a couple of words (or a small phrase) in order to add to the chat to get more information.

I'm not sure how much longer i'll keep using this if problems like this aren't resolved.

**Comment by mack-at-pieces** [comment]
Hi @mdeeter @itz-shubham - Earlier this week we released an update to Pieces OS, 10.1.8, that includes a few fixes to the text selection within the copilot. Could you please make sure you are updated to the latest, and then refresh your instance of VS Code, and try again?

Thanks!

**Comment by itz-shubham** [comment]
@mdeeter Thanks for the update. Now I can copy the individual text by `Command + C`. 
@rosie-at-pieces, you can close this issue

**Comment by rosie-at-pieces** [comment]
Fixed with release 10.1.8! Let us know if you have any further issues with this.
