### ISSUE TITLE
Codespaces Not Working - no login, install, refresh VSCode, etc. loop

### ISSUE THREAD

**Issue by GLStephen** [pieces-app/support#188]
### Software

Pieces OS, VS Code

### Operating System

Windows

### Your Pieces OS Version

9.0.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When attempting to use the VSCode plugin in Codespaces there seems to be no communication with the local Pieces OS. The plugin says login is requried (which I'm already logged in locally), then tries to reinstall base components, then recommend reloading VSCode. This loop never stops.

When I drop out of the codespace back to local I get what looks like a proper connection to pieces OS.

**Comment by caleb-at-pieces** [comment]
Hello @GLStephen !

In order to get the VS Code extension working while using the Code Spaces feature, you must set up a cloud proxy to Pieces OS using ngrok or a similar tool, and use the Custom Url setting in the VS Code extension.

Here's a guide on youtube for how to do this: https://youtu.be/sbgIaK9kpu4?feature=shared&t=426
Here is some written documentation on this feature: https://docs.pieces.app/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance#getting-started

Please keep in mind that setting up a cloud proxy to your Pieces OS instance will end up creating a URL that will expose your Pieces data and Pieces OS endpoints to the open internet!
