### ISSUE TITLE
Pieces has lost my snippet library

### ISSUE THREAD

**Issue by twilwa** [pieces-app/support#224]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

9.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I forget the error message now, but I beleive one did pop up, or there was something unusual that happened. In any case, I used to have a relatively extensive snippets library stored -- now I have one snippet, heh. 
![image](https://github.com/pieces-app/support/assets/111034762/028b3db5-edf6-4679-9c0b-15da748659ca)

I will mention that I use WSL2, and generally have to re-enable the WPE every time I reopen the application (separate issue but maybe relevant). Unfortunately don't have much more information, but happy to grab some logs if you point me in the right direction

**Comment by mark-at-pieces** [comment]
Hey @twilwa I'm sorry you are experiencing this issue, do you by any chance use Pieces on Multiple Machines or on Multiple user accounts?

if this is the case they are likely still around but just on that machine/user account since the Pieces data stay local and never leaves your machine, unless you opt into shareable links/gist/ or backups.

if you would prefer to hop on a call to debug in rt here is my calendar link https://calendar.app.google/JwFZafF4tKBh5reFA
