### ISSUE TITLE
Snippets not showing in VS Code while working on WSL

### ISSUE THREAD

**Issue by intothebeans** [pieces-app/support#243]
### Software

VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.5

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I'm having an issue viewing my saved snippets when working on WSL in VS code. Copilot connects to Pieces OS on the host machine fine, and when I run VS Code without a remote connection the snippets show up. I've attempted troubleshooting by deactivating all other extensions, and adding the incoming firewall rule. These did not solve the problem.

**Comment by caleb-at-pieces** [comment]
Hello @intothebeans !

I believe the issue here is that network requests from your WSL instance are being blocked by either the firewall, or an antivirus, or potentially something else.

I would love to hop on a call with you to debug why this is happening on your machine! Here's my booking link: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ3IijT1qgm0GgFeIllIuyy5ehWktuYQiPI6jegH4HlNGApAOMMVPiWCcoj_2aPfvgUiDmHHKcQE

Some things you can also try is attempting to make a curl request to Pieces OS from your WSL instance:

1. make sure Pieces OS is running on the windows host machine
2. run `grep -oP '(?<=nameserver\s)([0-9]{1,3}\.){3}[0-9]{1,3}' /etc/resolv.conf` on the WSL instance to get the LAN IP address of the host machine
3. from the WSL box rn `curl http://{LAN IP address of host machine}:1000/.well-known/health`
4. if WSL is able to reach Pieces OS it should output 'ok'

Do you have an antivirus running on your windows machine?

Again it would be absolutely excellent if we could hop on a call and debug this!

**Comment by intothebeans** [comment]
I set the custom URL in the extension settings to the local IP address and that solved the issue. Thanks!
