### ISSUE TITLE
Gemini doesn't pick up live context

### ISSUE THREAD

**Issue by Idrinth** [pieces-app/support#284]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Trying to get live data from a browser failed in todays session with Gemini refusing to access live data. See https://www.youtube.com/live/K3O0JTwz4JE?si=KjZ42ZfdEN5eZ0_u&t=6337

**Comment by mark-at-pieces** [comment]
Hey @Idrinth thanks for adding a ticket, I see you added a like to Jim's live stream. Could be a number of issues here that are going on that we would like to see in order to properly diagnose this issue.

That being said currently Live Context support with Gemini models is stuff under development.(IE workin on the prompts that will work properly to ensure we get the highest fidelity results). We are currently looking to massive improve our Gemini stack w/ primpts accorss the board start tuned for this update in future releases.

In the mean time, GPT-4o should work well with Live Context! please have a look and let us know what you think, and let us know if you run into an issue here with this model!

**Comment by Idrinth** [comment]
hi @mack-at-pieces , I just offered to create the issues in Jim's stead - tried to provide any information possible. This is the only one I couldn't reproduce due to not using live-context myself. That is why I added the link to the stream part where the issue happens instead,

Thanks for the quick feedback!

**Comment by sam-at-pieces** [comment]
This was resolved with an update to the OCR library.
