### ISSUE TITLE
Snippets gone after update

### ISSUE THREAD

**Issue by dotnetemmanuel** [pieces-app/support#30]
Updated Pieces OS this morning and was logged out of Pieces Desktop client on Windows 11. After I logged back in, my snippets were gone.

**Comment by mack-at-pieces** [comment]
Hey @dotnetemmanuel Thanks so much for this. Do you have a few minutes to hop on a quick video call to troubleshoot live?

**Comment by dotnetemmanuel** [comment]
Might be difficult right now, but would Monday work? Where are you guys at? I am in Sweden.

**Comment by rosie-at-pieces** [comment]
Hi @dotnetemmanuel so sorry for this! We have discovered the cause of this issue with another user.

In an effort to fix an issue related to OneDrive syncing users Documents folder, the latest update (Pieces OS 7.2.0) included a solution that ended up not properly functioning with users who use OneDrive, but don't sync (or at least don't aggressively & automatically sync) their local Documents folder.

As a result, this is causing your instance of Pieces OS to point to a location where your snippets are not present. Thankfully, your snippets are not lost or deleted and we can easily recover them.

If you'd like to connect to manually recover them sometime today, we'd be happy to hop on a quick call to do so at any time, just fill out [this form](https://getpieces.typeform.com/to/mCjBSIjF#page=docs-sidebar). Otherwise, our team is working on a hotfix that we will release ASAP.

For others, if you're a Windows user that has successfully saved snippets to Pieces and is now experiencing this issue where your snippets are no longer appearing, please [reach out to us](https://getpieces.typeform.com/to/mCjBSIjF#page=docs-sidebar) and we will be happy to help you ASAP.

We'll update this ticket when the release is out!

**Comment by rosie-at-pieces** [comment]
Just as a follow up to this - version 7.2.2 was released yesterday and should have resolved this issue without further action for everyone. If you are still experiencing issues please don't hesitate to reach out!

**Comment by dotnetemmanuel** [comment]
@rosie-at-pieces @mack-at-pieces 
All snippets are back after latest update (7.2.2)
Thanks for the amazing spped of your support!

**Comment by dotnetemmanuel** [comment]
Well, after update 7.4.2, they're gone again

**Comment by mark-at-pieces** [comment]
> Well, after update 7.2.4, they're gone again

are you available for a short chat?
