### ISSUE TITLE
Issue with remote desktop

### ISSUE THREAD

**Issue by hope205** [pieces-app/support#313]
### Software

VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I encountered this issue while trying to use the piece extension in my WSL. The piece's extension gives issues anytime I try to use it in the Ubuntu remote desktop environment. This is an image of the issue it shows. I already tried the troubleshooting method on your website by creating a new port but it still didn't work.

![issue](https://github.com/user-attachments/assets/dce2b29c-93cb-465c-8224-9d1b3ab795cc)

**Comment by caleb-at-pieces** [comment]
Hello @hope205 , I recently have updated these docs to show there is another strategy you can do to resolve this problem, hopefully it will have a higher success rate than the firewall rule:

You can read about it on our docs page here: https://docs.pieces.app/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance#pieces-os-is-not-connecting-on-wsl

The section about enabling mirrored networking mode for your WSL instance is what you are looking for. Following that guide you should be good to go, please let me know otherwise! If needed we could definitely hop on a call and debug this together, that will probably lead to the fastest resolution, you can schedule with me here: https://calendar.app.google/9Mj3jqt7syq3y4mX6

As a note: mirrored networking for WSL does not work on Windows 10, you must have Windows 11 installed. Also, you can check if mirrored networking is enabled by running the following command on a WSL terminal: `wslinfo --networking-mode`

**Comment by hope205** [comment]
I tried it on my pc and its still showing the same error. I will schedule a call on your calender now

**Comment by hope205** [comment]
Thanks for helping me out with the issue man. It's working perfectly now

**Comment by caleb-at-pieces** [comment]
> Thanks for helping me out with the issue man. It's working perfectly now

Awesome! Glad to help.

For posterity I will mention that the issue after enabling mirrored networking on WSL was that the .wslconfig file had an extension of .txt, removing the .txt extension resolved the issue!

**Comment by hope205** [comment]
Okay, no problem. Thanks for your help
Best regards
Oluwatimilehin Ogidan

ap-star.webflow.io

**Comment by Foxfire1st** [comment]
https://docs.pieces.app/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance#pieces-os-is-not-connecting-on-wsl

the link is down. How can I resolve that issue?
