### ISSUE TITLE
No response to the Prompts

### ISSUE THREAD

**Issue by shoaibkhan5676** [pieces-app/support#351]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![Screenshot (1)](https://github.com/user-attachments/assets/750f017a-58b6-460d-8f23-8e986cd51daf)
When i give any prompt as you can see in screenshot it doesn't give me any response and still loading

**Comment by mentariochain1** [comment]
same here

**Comment by mentariochain1** [comment]
<img width="2056" alt="Screenshot 2024-08-08 at 6 39 09 PM" src="https://github.com/user-attachments/assets/6098fe1f-5305-4817-8ccf-9024fe8c56dc">

**Comment by GimpyHand** [comment]
I have been having the same issue for 2 days. Tried on multiple systems (PC and laptop), 2 different os (windows 11, ubuntu), 3 networks (wi-fi and ethernet), and multiple AI models.

**Comment by mark-at-pieces** [comment]
Very interesting do any of these machines have a Firewall that might be blocking our requests?

Also if you still having issue please feel free to schedule some time on my calendar

https://calendar.app.google/T2d9gTE4rRMnyH3dA

same goes for everyone^^

**Comment by GimpyHand** [comment]
> Very interesting do any of these machines have a Firewall that might be blocking our requests?
> 
> Also if you still having issue please feel free to schedule some time on my calendar
> 
> https://calendar.app.google/T2d9gTE4rRMnyH3dA
> 
> same goes for everyone^^

One has a company firewall system, Sophos, but it worked on this system until a couple days ago. The other is a completely new, fresh install of Ubuntu with just pieces installed.

**Comment by rosie-at-pieces** [comment]
Hi everyone - just an update. We did find at least one user who is experiencing this scenario because they are using an invalid openAI API key so please double check that if you've entered one, and also double check that you didn't already hit your rate limits/quota. 

This issue was resolved with a different user by doing an full uninstall and reinstall so you can always try that. 

And finally, we are releasing PiecesOS 10.1.0 very shortly (likely tomorrow evening eastern timezone) which should resolve some of these scenarios. Please keep an eye out for that and if you are still experiencing issues after updating to that version please use [this link](https://calendar.app.google/T2d9gTE4rRMnyH3dA) to set up a quick chat with Mark! 

Also - if you try any of these solutions, please report your findings here for others to see!

**Comment by mack-at-pieces** [comment]
Hey @GimpyHand @mentariochain1 @shoaibkhan5676 yesterday we released Pieces OS 10.1.0 and Pieces Desktop 3.1.0 - can you please update and let us know if you are still having issues? Thanks!

**Comment by mentariochain1** [comment]
> Hey @GimpyHand @mentariochain1 @shoaibkhan5676 yesterday we released Pieces OS 10.1.0 and Pieces Desktop 3.1.0 - can you please update and let us know if you are still having issues? Thanks!

Yes, now it's work great. Thanks.

**Comment by GimpyHand** [comment]
> Hey @GimpyHand @mentariochain1 @shoaibkhan5676 yesterday we released Pieces OS 10.1.0 and Pieces Desktop 3.1.0 - can you please update and let us know if you are still having issues? Thanks!

Everything seems to be working well again. Great work!

**Comment by mack-at-pieces** [comment]
Thanks @GimpyHand @mentariochain1 . Going to close down this issue. If you experience anything else, you know how to get ahold of us! Appreciate your time and help 💪🏼
