### ISSUE TITLE
Pieces OS Ubuntu Server Not Starting

### ISSUE THREAD

**Issue by Omarplayz233** [pieces-app/support#394]
### Software

Pieces OS

### Operating System / Platform

Linux

### Your Pieces OS Version

10.1.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I wanted to start pieces-os command to start it with the pieces-cli package, using ubuntu server ofc, here's the details if you want to:
```
omarplayz@omarplayz-ubuntu:~$ neofetch --off
OS: Ubuntu 22.04.4 LTS x86_64 
Host: Extensa 5230 0100 
Kernel: 5.15.0-119-generic 
Uptime: 2 hours, 27 mins 
Packages: 954 (dpkg), 10 (snap) 
Shell: bash 5.1.16 
Resolution: 1280x800 
Terminal: /dev/pts/0 
CPU: Genuine Intel 575 (1) @ 1.995GHz 
GPU: Intel Mobile 4 Series Chipset 
Memory: 707MiB / 2898MiB 
```
so when i tried running pieces-os, it just like replied with a blank, pretty normal, right? but when i tried to check using `pieces version`, it popped like this:
![image](https://github.com/user-attachments/assets/4145c6c9-0410-412f-b4ce-9b41f43750f2)
even though the team told me to run some commands, it just doesn't respond:
![image](https://github.com/user-attachments/assets/82411ae3-3f60-4e1f-90da-546027f7af66)
even reinstalling:
![image](https://github.com/user-attachments/assets/e2614287-c168-4294-9c6e-ba06c2d42833)

**Comment by nathan-courtney-pieces** [comment]
Pieces OS likely won't work out of the box in headless environments due to missing graphical dependencies that the application relies on. 

You are welcome to run: 

`pieces-os --debug --verbose` 

To get a detailed output of the process and to potentially catch any failures. 

Pieces OS is built with Flutter so you may need some of these additional libraries installed: 

`sudo apt-get install libgtk-3-dev libgl1-mesa-glx`

You are welcome to post the output of the debug command and we can have a look.

**Comment by Omarplayz233** [comment]
sorry for being late, but after installing the packages, i ran the debug BUT it wants a display, but i have an ubuntu server but is it required to have one?
here's the result:
```
omarplayz@omarplayz-ubuntu:~$ pieces-os --debug --verbose

(os_server:5732): Gtk-WARNING **: 20:55:42.272: cannot open display:

**Comment by Omarplayz233** [comment]
well i have to close it since you need an Xorg display server in order for pieces-os to start
