### ISSUE TITLE
No Password Reset Link

### ISSUE THREAD

**Issue by Oliver-Turp** [pieces-app/support#40]
### Software

Desktop Application

### Operating System

Windows

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Note: `The issue is on the browser window but I don't have that option under software`

I just made my account with a google generated password. For whatever reason google didn't save it. I'm trying to reset it but I've been waiting over 30 minutes for a reset email. Nothing in my inbox or junk folders. Tried sending it again but nothing. How long should this take?

I tried reporting this on discord but I was told to make a bug report on GitHub.

**Comment by mack-at-pieces** [comment]
Hi @Oliver-Turp - Thank you for reporting this.

When making your account, did you click the option, "Don't have an account? Sign up."? Or did you click the option to "Continue with Google"?

**Comment by Oliver-Turp** [comment]
No I signed up manually with my email address. Since then I read another open issue regarding needing the same email address as your account to link github/google/microsoft so I made a second account by signing in with github as my google&github email is different from my usual sign up email which is a microsoft account

**Comment by mack-at-pieces** [comment]
> No I signed up manually with my email address. Since then I read another open issue regarding needing the same email address as your account to link github/google/microsoft so I made a second account by signing in with github as my google&github email is different from my usual sign up email which is a microsoft account

Okay great! And are you still looking to change the password for the original account you created, or are you successfully up and running using the GitHub/Google accounts?

**Comment by Oliver-Turp** [comment]
> > No I signed up manually with my email address. Since then I read another open issue regarding needing the same email address as your account to link github/google/microsoft so I made a second account by signing in with github as my google&github email is different from my usual sign up email which is a microsoft account
> 
> Okay great! And are you still looking to change the password for the original account you created, or are you successfully up and running using the GitHub/Google accounts?

I mean I'm up and running on the sign in with X method, but the manual sign up and subsequent password reset link system just doesn't work. I know this is a WIP project still but the user experience isn't great at times.

**Comment by mack-at-pieces** [comment]
Hey @Oliver-Turp - Thank you for this info. I'm glad you're up and running here and I appreciate the feedback regarding the reset password experience. I understand it can be a little clunky at times and we're working to do our best to make it better.

Not receiving an email to reset your password is actually a security measure to prevent passwords from being reset by unauthorized users.

With Pieces, there are few ways to sign in/connect accounts:
1. Via Custom OAuth using an arbitrary email & password
2. Via a Social Auth provider such as Google or GitHub
3. Via Custom OAuth using a Microsoft account (this is a little tricky)

The funnels can be visualized in this screenshot:
<img width="445" alt="Screenshot 2024-01-17 at 4 27 33 PM" src="https://github.com/pieces-app/support/assets/30325757/d3373740-7a31-466b-9cef-fce985370cfe">

In the event you are a Social Auth user (if you signed in with Google), clicking the Reset Password option will result in no follow-up email since your authentication credentials are technically handled with the social provider (Google). To reset your password in this case, you must do so via Google (Or the other provider).

In the event you are a Custom OAuth user, the Reset Password option will attempt to match the email you type to reset with a Custom OAuth email we have on record and dispatch an email accordingly. If no email is found, or an email is found but for a Social Auth provider, no email will be sent.

I'd love to help troubleshoot this for you to try and see what went wrong. If willing, could you please ping me in the Pieces Discord via DM with the emails you've signed into Pieces with so we can troubleshoot? My username is just Mack Myers.
