### ISSUE TITLE
Unable to Restart Pieces OS

### ISSUE THREAD

**Issue by webolution** [pieces-app/support#413]
### Software

Pieces OS

### Operating System / Platform

macOS Sequoia

### Your Pieces OS Version

10.1.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Unable to restart for update...

<img width="343" alt="Screenshot 2024-09-26 at 10 53 38 AM" src="https://github.com/user-attachments/assets/a0f32138-290c-4b4d-a6e1-7875d335aa42">

When I click restart, nothing happens. I have restarted and it did not fix the issue.

**Comment by OverHealz** [comment]
I have this issue as well.same MacOS.

Pieces is almost useless at his point

**Comment by nathan-courtney-pieces** [comment]
Hello @webolution @OverHealz 

There was a bug in 10.1.7 that would hang the UI in the drop down window thus not allowing you to interact with it. That has since been patched. 

Killing the process in Activity Monitor and relaunching should be enough to allow it to update to the latest version. 

If that is not working for you, simply running the `Pieces.pkg` installer from our website again should overwrite the apps to the latest version. Your personal data associated with the app will not be affected. 

Let me know if you are still having issues after trying these methods out!

**Comment by webolution** [comment]
That worked for me. Thanks!
