### ISSUE TITLE
Can't Preview Markdown Files after installing Pieces

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#446]
Original ticket: 
Ever since installing Pieces I can't preview markdown files on VS

Note: this issue was created automatically from an offline service ticket.

**Comment by judson-at-pieces** [comment]
https://drive.google.com/file/d/1Hxnbsum2aGueTYIf3Xcl9RXLg45HS33i/view?usp=sharing

This video should resolve the issue. The issue was that the hotkey command combo (cmd+shift+v) for previewing markdown files was being **overridden** by the Pieces: Save Current Selection. 

To fix this, press cmd+k+s (in that order) to open up the keyboard shortcuts menu, then type in "Save current selection" and re-map the hotkey command to something else that is not currently being used--like [cmd+shift+'], which is what I do in the video. I then checked that the original Preview Markdown keymapping was intact by searching `Preview Markdown`--you can see that it still retains the original keymappoing, which is cmd+shift+v. 

I then navigated back to my .md file and pressed cmd+shift+v and demonstrated how the live preview of the .md file feature works properly.

**Comment by john-walter-munene** [comment]
I appreciate the quick response. I've resolved this. Thank you.

**Comment by rutvik-pieces** [comment]
Closing this issue as resolved.
