### ISSUE TITLE
Subject: Live Context Feature Not Working

### ISSUE THREAD

**Issue by rohitYT04** [pieces-app/support#458]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

Pieces OS 10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi Pieces Support Team,

I'm having trouble accessing the Live Context feature in Pieces. I've tried [list steps you've taken, e.g., restarting the app, checking my plan, etc.], but the feature still isn't working.

Could you please help me troubleshoot this issue?

Thanks,
[Rohit Paul]
[kamardanga591@gmail.com]

**Comment by rosie-at-pieces** [comment]
Hi @rohitYT04 I'm so sorry you're having trouble using Live Context. Can you let us know specifically what isn't working - are you unable to turn the Long-Term Memory engine on, or are you receiving an error, or is it on and running fine and just not getting good answers when you have Long-Term Memory selected as context?

**Comment by mark-at-pieces** [comment]
Hey there @rohitYT04 Thanks for reaching out, we are sorry you are experiencing issues with the Live Context within the application.

Since our original release of LMT1(the Engine that drives Live Context) we have seen a few issues mainly due to machine specific configurations, it would be super valuable for us to schedule some time to chat to we can take a look at your set up to see if maybe there is a little bug on our side or something easy that we can adjust to ensure the Live Context works flawlessly.

Here is a link to my calendar (https://calendar.app.google/VcptMnyLirC6HKpV8)

Also reset assured we will be doing what ever it take to get you up and running!

**Comment by johnkennyuk** [comment]
Similar issue here too, it has worked in the past but now it won't enable in Pieces OS, not from plugins nor from the task tray menu, but the switch does activate in VSCODE ext & Pieces Desktop app but then copilot chats wont proceed from the notice informing that LTM is not enabled in OS??

**Comment by mark-at-pieces** [comment]
Hey @johnkennyuk && @rohitYT04 Please retry this feature, it appears this issue is now resolved w/ 11.0.0

closing this issue for now, if this is not resolved please reopen
