### ISSUE TITLE
AI cannot read files for context?

### ISSUE THREAD

**Issue by Oliver-Turp** [pieces-app/support#64]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

7.2.6

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When using the "attach files" for context during a copilot chat, the bot often cannot read them (I assume). I'm finding directly pasting code into the message field a better way to get responses. But then I often run into message length issues (I assume again, see my other open issue)

![image](https://github.com/pieces-app/support/assets/55669423/9e4fb534-8b67-406f-b079-79ae54003dc7)
![image](https://github.com/pieces-app/support/assets/55669423/d468c952-1e75-4c0c-a8a8-616b6688bcb4)

**Comment by caleb-at-pieces** [comment]
Hello,

Thank you for reaching out to us about this! This is a commonly described problem by multiple users and it's certainly one that is driving the direction of where our Copilot will be in the future.

A short explanation of this problem is: your prompt is acting like a search query with your context as the search space, so try to also mention something that is semantically present in the context in order for this to work as expected! If that doesn't work you may need to reduce the amount of context that you have selected in that conversation.

Another good rule of thumb is adding a file name into your prompt will generally not help the Copilot perform better.

For example instead of asking the Copilot 'Within the file context's you have access to asses if I exported and imported properly, did I export and import `resetPrismaTickets` properly?'. Ask something more along the lines of: "What do you know about the `resetPrismaTickets` function?'" and you will likely see better results.

In order to solve this problem we are thinking about introducing a few different modes into the Copilot: general questions mode, small context mode, and large context mode. Which will allow you to configure the copilot to match your expectations (for this case it would be small context mode, which would perform similarly to copying and pasting code with your prompt).

These modes will be a new edition to our Copilot UI, so as a user you can select which mode you plan to use, allowing us to better align the function of the Copilot to your expectations.

Hopefully this is a good enough explanation, we definitely see and feel your pain here! Hang tight and we should be able to roll out some great improvements very soon for this.

**Comment by rosie-at-pieces** [comment]
closed due to inactivity
