### ISSUE TITLE
Can't Find Saved Materials In VS Code

### ISSUE THREAD

**Issue by anowarzz** [pieces-app/support#74]
### Software

VS Code

### Operating System

Windows

### Your Pieces OS Version

Pieces for Developers 2.9.4

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I have installed pieces desktop application and i also have vs code extention for pieces installed.  but in my vs code **pieces explorer** section , i can't find the option of saved materials.  how can i find my saved snippets quickly in vs code?? 

![image](https://github.com/pieces-app/support/assets/108596949/b7f1d8bb-b968-4c38-95c9-ffe2539e803d)

**Comment by anowarzz** [comment]
The issue is solved. it was from my end though. Thank you @caleb-at-pieces

**Comment by caleb-at-pieces** [comment]
> The issue is solved. it was from my end though. Thank you @caleb-at-pieces

Happy to help!

For people who may be revisiting this issue in the future, here is the solution for this:

I suspect you may have accidentally dragged and dropped the saved materials somewhere else within your IDE. For reference, each view in VS Code can be moved elsewhere by clicking on the view header and dragging it.

In order to locate where it may be, you can run a command in VS Code:
1. open the command palette by doing `ctrl + shift + p`
2. search `snippetTree.focus` and run the command that is titled: 'Pieces Explorer: Focus on Saved Materials view'
