### ISSUE TITLE
VS Code/Obsidian "Please update your Pieces OS" error Linux

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#96]
### Software

Pieces OS, VS Code

### Operating System

Linux

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Linux users are experiencing a "Pieces OS needs to be updated!" in their VS Code or Obsidian plugin. The 8.0.0 release for Linux is delayed, making it out of sync with our Obsidian and VS Code plugins. We hope to get this release out today or tomorrow, will keep everyone updated here. 

You can downgrade your Pieces Extension in the plugin marketplace in the meantime. 

Our apologies for this inconvenience!

**Comment by TENSAEA** [comment]
please fix it ASAP

**Comment by AnmolDotX** [comment]
**Okkay let me explain it, as am also facing the same issue:**
Today I came across pieces and went through the installation process as per the instruction given on the offical site. I did it and all the installation went well, as expected.

![Screenshot from 2024-02-21 15-13-58](https://github.com/pieces-app/support/assets/105695160/eff73a1f-74d8-4246-a375-17394b89a50c)


Now when I tried to launch pieces-os, it only showed up this some sort of notification panel type of thing, at the top of my desktop screen.

**Launch Icon:**
![Screenshot from 2024-02-21 15-10-46](https://github.com/pieces-app/support/assets/105695160/d524df92-fb5a-4975-949c-7120a0f67516)

**pieces at top:**
![Screenshot from 2024-02-21 15-11-00](https://github.com/pieces-app/support/assets/105695160/2cd2dc5b-9f1a-46e4-ae09-da9a70fc3015)



I didn't knew till now if it is installed properly or not, but nevermind let's process further; Now I opened the pieces-for-developers and went through the setup process and also signed up with my github account. It showed up its UI but the responses were too slow as compared to that of online chatGPT or Gemini. I thought it might be because it was first time I have launched the pieces, so it may take some time to get used to my code style and will eventually train itself with time:


![Screenshot from 2024-02-21 15-23-42](https://github.com/pieces-app/support/assets/105695160/11f10506-ae4a-4e38-870c-2b96016ffef3)
![Screenshot from 2024-02-21 15-23-28](https://github.com/pieces-app/support/assets/105695160/016f8b5a-1198-4e00-8d6f-a911cd5cda63)




But the problem was not only that, when I opened the VScode, so that I can use pieces-copilet there, it showed me to update the pieces-os, as it is not able to launch it.

![Screenshot from 2024-02-21 15-10-32](https://github.com/pieces-app/support/assets/105695160/011b7404-ac39-4dd7-a04b-44ef81ea472a)



and when I tried to click on launch, it showed, "please make sure pieces-os is installed": but actually it is installed so I don't know where is the problem. Do you guyz see this?

![Screenshot from 2024-02-21 15-10-18](https://github.com/pieces-app/support/assets/105695160/76beeed6-ea7b-4280-9520-b797679bd405)

**Comment by AnmolDotX** [comment]
Also for the reference I have Ubuntu 22.04 LTS installed, @rosie-at-pieces , I think in this way you can reproduce this. Would appreciate if you guyz do this as fast as you can. You call are already working great, hope for the further fast bug fixes.

![image](https://github.com/pieces-app/support/assets/105695160/ce1bfccb-0f0e-47a7-b790-1a011979105f)

**Comment by TENSAEA** [comment]
I think for the mean time you can downgrade the version on vs code and It works for me.

**Comment by TENSAEA** [comment]
Thanks It works now.

**Comment by AnmolDotX** [comment]
That's great, it's working now. Thanks!
